In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df = pd.read_csv('Duplicate Question.csv')
print(df.shape)
df.sample(5)

(404290, 6)

,id,qid1,qid2,question1,question2,is_duplicate
389481,389481,121207,478069,How do I manually upgrade my Android 4.4.2 to ...,How do I upgrade my andriod 4.2.2 to 5.1?,0
140845,140845,223748,223749,Where do I get songs like Moon River?,"What's the meaning of the lyrics in the song ""...",0
361259,361259,284425,491078,What kind of employment can an H4 visa holder ...,Can H4 visa holders take any unpaid internships?,0
261975,261975,378219,378220,What are some good Salads recipes?,How can we mitigate the pilot pollution from o...,0
66688,66688,49437,1063,Is World War 3 coming?,Are we heading toward World War 3?,1

 Since the data is too big to handle and my machine doesn't have that much capacity to perform the task on this much large data set

In [3]:
df = df.sample(30000)
df.shape

(30000, 6)

In [4]:
df.isnull().sum()

id              0
qid1            0
qid2            0
question1       0
question2       0
is_duplicate    0
dtype: int64

In [5]:
df.duplicated().sum()

np.int64(0)

In [6]:
df.sample()

,id,qid1,qid2,question1,question2,is_duplicate
122883,122883,198797,198798,How capable is the M60 MBT in modern combat?,Just how fast would an M4 Sherman get wiped ou...,0

# Extracting the required columns to for BoW

In [7]:
ques_df =  df.iloc[:,3:5]
ques_df.head()

,question1,question2
128471,Why did Ryan Lochte lie about getting robbed a...,"In the 5th book, why does Harry say that he co..."
64342,Why do parents want their kids to become a doc...,Why do most Asian parents want their children ...
247041,How do you get rid of a swarm of bugs in your ...,I am first year student at bcom hons in delhi ...
193729,What are the best songs to put on a running/wo...,What are the some of the best songs for the gy...
366149,What are the best and quickest ways to reduce ...,What is the effective ways of reducing stress?

# Applying Bag of Words

In [8]:
from sklearn.feature_extraction.text import CountVectorizer 
cv = CountVectorizer(max_features=3000)

# Merging the q1 and q2 together so that we can apply the BoW together on both questions

In [9]:
# Merging the questions in single list 
ques = list(ques_df['question1'].to_list() + ques_df['question2'].to_list()) 
ques

['Why did Ryan Lochte lie about getting robbed at Rio 2016 when he could have just kept quiet?',
 'Why do parents want their kids to become a doctor?',
 'How do you get rid of a swarm of bugs in your basement?',
 'What are the best songs to put on a running/workout playlist?',
 'What are the best and quickest ways to reduce stress?',
 'How can I delete my blocked Facebook account by gmail account?',
 'Is it safe to buy an unlocked phone from eBay India? What if I receive a defective product as the seller has specified no refund? Should I buy it an HTC One m8 Verizon unlocked version?',
 'Where is the safest place to shoot somebody so he/she does not die immediately?',
 'How will Trump or Clinton presidency affect foreign students?',
 'How good is to work at Google?',
 'Does Arrakis work well with EC2?',
 'What is the difference between the ThinkPad and IdeaPad?',
 'What are the health benefits of eating oxtails?',
 "What are the best new products in technology that people don't know about?",
 'Why do people ask questions on Quora instead of Googling it?',
 "What's the best way to learn playing guitar?",
 'What are some good colleges for business majors?',
 'Computer Peripherals: Who invented the mouse?',
 'If Britain decides to exit the EU, how would it affect the Indian Economy?',
 'What are some facts of British Indian Ocean territory?',
 'What is BJT?',
 'What are the achievements of USA Puppet Government in Iraq?',
 'What secret can you not share with anyone?',
 'What are the coolest facts about black holes?',
 "Can I become a billionaire gambler like 'Zeljko Ranogajec' who makes an betting turnover of billion of dollars? Do you think he is gifted gambler?",
 'What makes a person join ISIS?',
 'Why do evolutionists lock questions asking for a way to falsify the theory of evolution?',
 'Is OK to give money to beggars?',
 'What is the fastest way to raise your credit score?',
 'What are some tips for a bass clarinetist learning soprano clarinet?',
 'What are the applications and limitations of a threat and vulnerability management oriented strategy?',
 'How does short-term disability insurance work in Wisconsin?',
 'If Apache Drill and Impala both perform SQL on Hadoop, then what are the differences between each?',
 'Has anyone living in Kongka La Ladakh and using Quora seen a UFO?',
 'How do I get a job in Gulf Country?',
 'How are joules and calories related?',
 'I scored 570 in neet 2 . What would be my expected rank, in total from neet 1 & 2?',
 'What is potential differential and why is it important?',
 'What does it mean when Buddha says "There can be no companionship with a fool"?',
 'Is it better to sleep during the day or at night?',
 'If the president is impeached, who assumes the office?',
 'How can I train a recursive neural network?',
 "Where are Che Guevara's children?",
 'History tells us that India is a country of all religions. Sufism, the Bhakti movement, Buddhism, Jainism, Sikhism and other religions helped to build India into a more open-minded country towards religion. Is that true? How?',
 'How do I improve my communication skills in one month?',
 'Is there a recession coming in 2015-16?',
 'Who are some of your favorite Quorans?',
 'Is playing video games and watching TV cartoons bad for development of the brain of children under 5 years of age?',
 "How should Californians vote on 2016's Proposition 61?",
 "I'm 18. How can I make money online?",
 'What is the most efficient way to travel from Sacramento to San Francisco?',
 'What if my girlfriend wants our photos deleted?',
 'How do I earn a million dollars in 3 months?',
 'How good is a strawberry kiwi Jell-O?',
 'How do I sexually arouse my girlfriend?',
 'Who is the best skin doctor in Indirapuram Ghaziabad for complexion enhancement?',
 'How can I overcome my current situation?',
 'How did the U.S. deal with the ruling by the UN International Court of Justice in 1986?',
 "What are some things new employees should know going into their first day at Conn's?",
 'What will happen if I take 40 (200 mg) Tegretol?',
 'How do I get myself ill enough to be hospitalized?',
 'How can I use Reddit efficiently?',
 'What is the difference between dominant and recessive alleles?',
 'What was the status of black people in the Roman Empire?',
 'How do I treat acne scabs?',
 'How long does it take for damaged nerves to repair themselves?',
 'What is the Sahara, and how do the average temperatures there compare to the ones in the Colorado Plateau?',
 'How do I clear my criminal records?',
 'What are some good lyric prank songs for your best friend?',
 "Why don't people suffering from amnesia not forget fundamental things they learn, like their mother tongue?",
 'Which one is the best romantic movie?',
 "Have you ever had sex with a complete stranger? What's your story?",
 'Is it acceptable to use a fake Facebook account to join Quora?',
 'How do you view the Indian government\'s decision to fight "black money" by scrapping 500 rupee and 1000 rupee notes?',
 'What is the purpose of using ADC in electronics devices and gadgets ?',
 'What is the best food to eat on an empty stomach?',
 'How can I (a teen with mental health problems) get a job?',
 'What are some cool WhatsApp group names?',
 'Who is the best MCAT instructor in Lahore?',
 'How can I teach the difference between fruits and vegetables to my kindergarten kid for her exams?',
 'What is/are your most horrifying stories about ghost or any paranormal activities you ever faced?',
 'I have an untreatable and life-long disabling neurological disease. What is the easiest and most painless way I can commit suicide?',
 'What is photography?',
 'Who is voting for Donald Trump?',
 'If you could travel the speed of light, what would happen?',
 'What are some good online sources of free books?',
 'What is a good tagline for Facebook?',
 'How should I prepare for GSoC?',
 'Which residential college to choose in the University of Western Australia?',
 'Why some of my questions on Quora not answered by anyone yet?',
 'What is the best way to show on my LinkedIn profile that I am between jobs and looking for work?',
 'Which travel agency should I approach to travel to Manali from Kochi?',
 'Who was the most powerful warrior in the Mahabharata?',
 'What are the best websites to watch and download Hindi movies with English subtitles?',
 'What is the freezing point of a liquid?',
 'Who are some of the most underrated cricketers ever?',
 'What are some websites which can enhance my knowledge on different topics?',
 'Will Python take over R?',
 'Are there any online accounting systems for Small businesses adapted to Mexico?',
 'Who are the best personal financial advisors in Green Bay for people saving for retirement? What were your experiences with them?',
 'Is the word food singular or plural?',
 'What are the big, mega dance clubs in Singapore?',
 "Career Advice: What is the reason many engineering students can't get jobs in India?",
 'Documents for Indian passport?',
 '•• Who should be in charge of measuring a state’s success—its citizens, or other states?',
 'Why are Middle East countries called gulf countries?',
 'What is better: Apple or Google?',
 'What is the function of the cytoplasm in an animal cell? How is it important?',
 'What is art history?',
 'What are examples of cultural bias?',
 'How did smartphones changed the life of elderly?',
 'How do I stay motivated for school?',
 'What are some famous stories about Swami Vivekananda?',
 'How do I write a letter to the headmaster requesting him to submit project?',
 'If I delete my snapchat app will it erase my streaks?',
 'What is perfect age for marriage?',
 'When I run or exercise, is a 180 bpm pulse normal? Is it safe?',
 'How do I make 1000 dollars/day online?',
 'Where can I buy Samsung notebook 9?',
 'Where can I pay for active Twitter followers (not bots) for a small business? Which sites are reliable?',
 "What are the main reasons why students from the University of Nebraska at Kearney don't graduate on time?",
 'How true is the concept of karma?',
 "What are the 'best in class' companies and products everyone should know in 2017?",
 'What are the best places to visit in Kerala?',
 'Which is the best bike for teenagers to start Yamaha R15 or KTM RC 200?',
 'Why does video on Facebook buffer slower than video on YouTube?',
 'Why is 0/0 is not defined?',
 'When running for President of the USA, has there ever been a candidate that lost and re-run again?',
 'Which is the best Home Security Systems?',
 'How do I stick to my goals?',
 'Can I ever stop emotionally abusing myself?',
 'How many years does it take to become a CA?',
 'What is the funniest person you have ever met and why?',
 'What is it like being Korean American vs. Chinese American?',
 'Why did the government decide to scrap 1000 rupee notes and introduce a denomination of 2000 instead?',
 'What is the value of (0/0)?',
 'What anime uses Toon Boom or other similar 2D animation software?',
 'How did you know you were a sociopath?',
 'What is the impact of Islam in the present world?',
 'What happens if a person has black money and opts not to return it to the government?',
 'How powerful is Ghost Rider actually?',
 'What are some good science magazines I can get in India?',
 'What is ship science?',
 'What dirt is there on Bernie Sanders?',
 'In terms of tradition and mythology, why does Santa Claus live at the North Pole?',
 "Is getting one's wisdom teeth at the age of 12 normal?",
 'How do I make an Android application using Python?',
 'Why is Ajay Chandrakar so popular?',
 'What are the good things that happened in India which most people are unaware of in 2016?',
 'I gained knowledge about human psychology, but got set back in my career development. Was this a waste of time?',
 'Audio Equipment: What is the best Headphone under Rs 2K available in India?',
 'How do I get the PAN number if I know only the name of the person in India?',
 'I have a very insensitive and immature girlfriend. What do I do?',
 'Can i get pregnant the day after my period ends?',
 'How is the height of a place from sea level calculated? What method is used by scientists?',
 'Do you think too few Indians pay income tax?',
 'What are the innovative machine learning project ideas?',
 'Is there any method to unlock icloud id lock by anything?',
 'What does Google Scholar offer?',
 'What are the best sexy films?',
 'Do you have to do undergraduate research to get into graduate school?',
 'What purpose does compression serve when mixing?',
 'Why is kale good for you? What properties does it have?',
 'Why some computer PCBs have several traces in the shape of a serpentine? Why are they designed this way?',
 'How do I prepare for NDA written exam in 15 days?',
 'Who are some famous Filipino painters and the names of their paintings?',
 'What is the valid reason for India only getting a few medals in the Olympics?',
 'What is right assessment about Sadguru Jaggi Vasudev? Is he just loquacious or really attained knowledge and wisdom that saints are known to possess?',
 'Is dark matter a sea of massive dark photons that ripple when galaxy clusters collide and wave in a double slit experiment?',
 'Where can I get free Instagram followers?',
 'Do Stephen Hawking and Neil DeGrasse Tyson really believe CERN poses a danger to humanity and Earth itself?',
 'Which enzyme uses both NAD+ and NADP+ as a coenzyme?',
 "How would Donald Trump's win affect India?",
 'I want to stop comparing myself to others. What should I do? Can you help me?',
 'What are internet speeds like on planes?',
 "Why would a guy who doesn't love a girl get her pregnant?",
 'What is one thing you love about your spouse?',
 'Why are my all questions marked for improvement?',
 'Who would win a fight Bruce Lee or Muhammad Ali?',
 'Breaking Bad (TV series): Why did Gus kill Victor?',
 'What is traction in publishing an ICT project?',
 'What is a polite word or phrase to refer to someone who currently has, or is in the process of getting, tattoos or body art?',
 'Which is the highest point in ingineering which will give me highest salary after 20 years?',
 'Why does Obamacare cost so much and why is the opposition to it so strong?',
 'What is the iPhone 6 plus "touch disease"?',
 'What is devolution? What are the benefits?',
 'How should one deal with depression?',
 'Is it possible to implement Uniform Civil Code in India?',
 'What are the best horror movies that will keep you up at night?',
 'What is the interview process at JusPay Bangalore?',
 'What\'s the origin of the expression "Yippee Ki-Yay"?',
 'Are we near World War 3?',
 'Who has finished the Candy Crush Saga?',
 'Can we do local listings for stalls in shopping malls?',
 'How is fastudent.com?',
 'I would like to prepare for KVPY SX.How can I do it?',
 "How is the word 'dexterous' used in a sentence?",
 'What is the difference between hobbies and interest?',
 'Do chiropractors really work?',
 'Comebacks (replies): What is a good response when someone retorts "What do you want from me?"',
 'Who is a good marriage counselor in Pune?',
 "Do people have sex in Osho's ashram?",
 'What are some awesome things to do in Sydney that are not in the standard guide books?',
 'What’s your say?I know that the first year of MBA in IIM is hectic.But is it very hectic that at one point you regret joining IIM? Or is it enjoyable?',
 'Other than golf, what hobbies in 2014 (or better yet, the future) are going to be most conducive to building business relationships?',
 'What are some things new employees should know going into their first day at Consolidated Communications?',
 'What is your favorite Tom Hanks movie?',
 'Which is a suitable solar panel installation provider near Atwater, California CA?',
 'How do I prepare for JEE Advanced?',
 'How shall I prepare for AIIMS 2017?',
 'Do Americans girls actually like the British accent?',
 'How do I post ads in internet?',
 'How long does crystal meth stay in your system and how can I dilute it?',
 'Which are the best laptops to buy around 55k?',
 'As a legitimate massage therapist, how often does a client indicate they would like a "happy ending"?',
 "What are the best new Car gadgets that most people don't know about?",
 'How do I begin with my spiritual journey?',
 'What is C programming?',
 'How do the Americans view German people?',
 'Have you ever randomly met a celebrity, like Nicki Minaj?',
 'Is it normal to have thoughts of committing murder as a child? Am I a Psychopath?',
 'Is long distance relationship works?',
 'Is it true that the upcoming 2000rs and 500rs notes are going to come along with a ncp chip?',
 'What would happen if we deposit life on Mars with all the adequate resources for it? Will it adapt/evolve to survive the climate of Mars?',
 "Girl telling girl you're interested in her physically?",
 'How safe is an amusement ride that exerts centrifugal force?',
 'Would demonetization of 500 and 1000 rupee notes actually help in curbing black money in India?',
 'What is the difference between hatchbacks and surperminis?',
 'What are some funny jokes on Canadians?',
 'Why do our legs seem to be more muscled than our other body parts?',
 'Is the R.T. News channel as biased as the Western media would have you believe?',
 'Suppose in a given collection of 2016 integers, the sum of any 1008 integers is positive.Show that sum of all 2016 integers is positive?',
 'Who is best dermatologist in tirunelveli?',
 'Why is Donald Trump appeasing American Hindus?',
 "Why isn't Healthcare free to the American people?",
 'What is the diet of a woodlouse?',
 'What do I have to do to get white teeth?',
 'What are some unique and typical Colombian Spanish slang words?',
 'Why do people ask questions on Quora that are easily answerable via a quick internet search?',
 'What are the best porn ads?',
 'How can I differentiate a vein from an artery?',
 'Maryland Football Live Stream | Watch Maryland Terrapins Football Game Today Live Streaming Online?',
 'How were the Pyramids of Giza built?',
 'Why should I vote for Hillary Clinton and not Trump?',
 'What things can I do to show my exgirlfriend I have become a stronger non needy man?',
 'What is the history of Thanksgiving day?',
 'I started to use my first name after started working in US. Does it cause confusion cuz I used my middle name when I study in US and back at hometown?',
 'What is love according to girls?',
 'I have got admit for Information and Network Security MEng in University of Limerick, Ireland. Should I accept the offer?',
 'I am a Muslim female and I want to marry a Hindu boy. I am a Pakistani national. What can I do?',
 'What Is unit testing in c#?',
 'Any examples of  the mind-blowing, awesome arguments given in the court of law by which the case turned around?',
 'How do you say "A woman who loves to kiss." in simplified Chinese?',
 'The question was marked as needing improvement. Just now?',
 "What is Kim Guldberg's job?",
 'How do I build more confidence?',
 'What are some examples of stories where the characters journey into Hell and then return?',
 'How many restaurants are there in Italy? On average, how much does each restaurant spend (per year) on marketing?',
 'How many dates do you wait before asking a girl back to your place?',
 'What individuals and events in history are a source of pride for Guinea?',
 'Do people smell as they get old?',
 'Will a .44 magnum really blow your head clean off?',
 'Why do mosquitoes revolve in circles around our heads?',
 'What are some good words starting with the letter R to describe someone?',
 'Is 28 too old to graduate?',
 'How can I find out how long two people have been friends for on Facebook?',
 'How will be the exam pattern of GROUP 2',
 'What are the best novels in 2016?',
 "What's the difference between RAM and ROM?",
 "What's the difference between PU leather and real leather?",
 "My cousin still plays with dolls and she's 19. Isn't that way too old?",
 'If you could change a few things in Quora what would it be?',
 'Where can I learn ethical hacking in Kolkata?',
 'How did Celia Valli die? How old was she?',
 'What branch can I get in SRM main campus?',
 'If I add more salt than the saturation point of salt in water, what will happen to the excess salt?',
 'What role is a scribe going to play in the XAT exam for a 60% VH candidate?',
 'What is a typical day like for the President of the United States?',
 'What should we do when we feel empty?',
 'Is college really worth the energy?',
 'How do I start preparing for JEE just after class 10? Suggest some books also for beginners?',
 'What is the best forensic medicine books for medical students?',
 'How much CPU time is needed to mine 1 bitcoin?',
 'Should I go to IBS Hyderabad (ICFAI) for an MBA? Why or why not?',
 'Can I earn money on Quora?',
 'How long will it be before flight crews on airliners are replaced by on board computers and remotely managed systems similar to modern drones?',
 'I caught my son and daughter touching each other. What should I do?',
 'What is the difference between front end and back end development?',
 'What are examples of raw materials and their uses?',
 'What is the current status of Introduction of polymer currency notes in India?',
 'Should you let your baby listen to heavy metal?',
 'How do I analyze Winston Smiths character based on the Marxist lens in 1984?',
 'What are the best subwoofers for a mobile DJ?',
 'Where can I learn Haddop & big data in Chennai?',
 'What individuals and events in history are a source of pride for Cambodia?',
 'Why do we need to embrace multiculturalism?',
 'Is it possible to grow hair on natural wide forehead with natural ingredients?',
 'How it would be to join time for cat in february for cat 2017?',
 'What are similar sites like Quora?',
 'What will happen to Chinese students studying abroad in America now that Trump is president?',
 'How do you open an electronic safe if the battery is too weak to do the unlock mechanism?',

In [10]:
# Creating the Arrays of  questions q1 and q2 
q1_arr, q2_arr = np.vsplit(cv.fit_transform(ques).toarray(),2)
q1_arr.shape, q2_arr.shape

((30000, 3000), (30000, 3000))

In [11]:
# Merging the q1_arr and q2_arr 
temp_d1 = pd.DataFrame(q1_arr, index=ques_df.index)
temp_d2 = pd.DataFrame(q2_arr, index = ques_df.index)
temp_df = pd.concat([temp_d1,temp_d2],axis=1)
print(temp_df.shape)

(30000, 6000)

In [12]:
temp_df.head()

,0,1,2,3,4,5,6,7,8,9,...,2990,2991,2992,2993,2994,2995,2996,2997,2998,2999
128471,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
64342,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
247041,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
193729,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
366149,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
temp_df['is_duplicate'] = df['is_duplicate']
temp_df.sample(5)

,0,1,2,3,4,5,6,7,8,9,...,2991,2992,2993,2994,2995,2996,2997,2998,2999,is_duplicate
73244,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
144920,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
353821,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
214126,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
212610,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [14]:
from sklearn.model_selection import train_test_split 
x_train,x_test,y_train,y_test = train_test_split(temp_df.drop(columns='is_duplicate').values, 
                                                 temp_df.iloc[:,-1].values,test_size=0.2,random_state=1)

# Applying Algorithms to find out the Accuracy

In [16]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score 
from sklearn.metrics import ConfusionMatrixDisplay 

rf = RandomForestClassifier() 
rf.fit(x_train,y_train) 
y_pred_rf = rf.predict(x_test) 
print('Accuracy score for Random Forest -->', accuracy_score(y_test,y_pred_rf))

Accuracy score for Random Forest --> 0.7488333333333334

In [17]:
from xgboost import XGBClassifier 

xg = XGBClassifier() 
xg.fit(x_train,y_train)
y_pred_xg = xg.predict(x_test) 
print('Accuracy score for XG Boost -->',accuracy_score(y_test,y_pred_xg))

Accuracy score for XG Boost --> 0.7298333333333333